### ISSUE TITLE
A way to support ipv4 and ipv6 at same time

### ISSUE THREAD

**Issue by Salmela** [chrislim2888/IP2Location-Python#11]
IP2Location is currently distributing the ipv4 and ipv6 databases in different files. This library does not support opening both at the same time. So we need to load correct file based on the requested ip address, but there is no method to check which version needs to be loaded, so for now we used the private method `_parse_addr`. Our code looks something like this:
```python
iplocation = IP2Location()
if iplocation._parse_addr(addr)[0] == 6:
  iplocation.open('ipv6.bin')
else:
  iplocation.open('ipv4.bin')
return iplocation.get_all(addr)
```
If there is better way to support ipv4 and 6 at same time, can you please show how to do it? Or could you add public method that tells which ip database file is needed? For example:
```python
  def get_ip_version(addr):
    return this._parse_addr(addr)[0]
```

**Comment by chrislim2888** [comment]
Hi Salmela, our IPV6 database does support both IPV4 and IPV6 query. Have you try before?

**Comment by Salmela** [comment]
Thanks for reply. I just tested the IPv6 db and you are right. I guess this could be documented in better way that the IPv6 db contains also IPv4 addresses.
