### ISSUE TITLE
IP2Location binary

### ISSUE THREAD

**Issue by ggjersund** [chrislim2888/IP2Location-Python#12]
I'm wondering if IPv6 binary file also contains all the entries of the IPv4 binary file? I'm looking to do IPv4 & IPv6 lookups but the CSV format version only show `IPv4Comp` for all IPv4 fields in the IPv6 CSV file. I'd like to have them combined so that I only need to handle binary file. Is it possible, or do you supply these files by any chance?

**Comment by chrislim2888** [comment]
Hi ggjersund, our IPV6 binary file does support both IPV4 and IPV6 query. Have you try before you created the issue?

**Comment by ggjersund** [comment]
@chrislim2888 Awesome. Thanks for the help. Closing the issue.
