### ISSUE TITLE
IPV6 lookup is not working with Python 3.6

### ISSUE THREAD

**Issue by pinnareet** [chrislim2888/IP2Location-Python#13]
Error is attached in the screenshot:
![Screenshot 2020-05-31 09 35 24](https://user-images.githubusercontent.com/4829500/83343296-855e8080-a322-11ea-8a85-49fee8c965d0.png)

Since Python 2 is deprecated, it would be nice to have the library updated. Thanks!

**Comment by pinnareet** [comment]
Actually, the IP2LOCATION-LITE-DB11.IPV6.BIN also doesn't work for Python2

![Screen Shot 2563-05-31 at 10 00 21](https://user-images.githubusercontent.com/4829500/83343504-8c3ac280-a325-11ea-9b9f-c109b9e57984.png)

**Comment by ip2location** [comment]
Hi pinnareet,

We had tested the IP2LOCATION-LITE-DB11.IPV6.BIN for both version of Python, and they are working as usual. Please see the screenshots for the sample code used and the result.
![ip2location-python-ipv6-1](https://user-images.githubusercontent.com/6367210/83367260-3c700000-a3e6-11ea-88fa-ab09d647fa5d.png)
![ip2location-python-ipv6-2](https://user-images.githubusercontent.com/6367210/83367258-3aa63c80-a3e6-11ea-94d8-dd027263b742.png)

Are you using the latest version of the database file? We are using the latest version of database during our testing. Also, can you please share how do you configure and test, along with your full code? Thank you.

**Comment by pinnareet** [comment]
Thanks for your prompt response! It does work for me today. Sorry for the trouble. 

I tried it on google colab: https://colab.research.google.com/drive/1PA9R-1Mo0RBELPq08-bczBqh4xRUWSje#scrollTo=SprVhUNRvO9H uploading the database file locally. Maybe the file got corrupted while uploading.

**Comment by ip2location** [comment]
Hi pinnareet,

Glad to hear that your issue is solved.

I will close this issue ticket by now, but if you have any other issue, feel free to open a new issue ticket. Thank You.
