### ISSUE TITLE
Updates vs shared memory

### ISSUE THREAD

**Issue by pySilver** [chrislim2888/IP2Location-Python#14]
What would be the correct behaviour to handle updates when database is used in shared memory mode? 

There is a long running set of gunicorn processes that uses ip2location database in shared memory mode and some side job that updates database file periodically. Does mmap hanles updates itself or its developer responsibility to re-read database?

**Comment by chrislim2888** [comment]
Hi pySilver,

Mmap cached the database into the memor. Hence the developer will be required to restart the process to allow the mmap to cache the database again.

**Comment by pySilver** [comment]
Since its a global shared variable it's possible to attach a datetime property to it, so one can store shared variable creation time and refresh it from time to time :)

**Comment by chrislim2888** [comment]
Hi pySilver,

We appreciate your feedback on this. However, we do not have plan to implement a new datetime value due to the BIN database is monthly update basis.
