### ISSUE TITLE
Debug "print" statements left in code

### ISSUE THREAD

**Issue by nighttardis** [chrislim2888/IP2Location-Python#17]
With the latest release it looks like there are a couple debug "print" statements that were left in, the are on line 569 and 584 in IP2Location.py. Can they be cleaned up or at least changed to be optional?

**Comment by ip2location** [comment]
Hi nighttardis,

We had removed the debug lines, and had released a new update. You can get from [Pypi](https://pypi.org/project/IP2Location/8.6.4/).
