### ISSUE TITLE
IP2Location giving wrong geolocation with updated database in Python 3.6.

### ISSUE THREAD

**Issue by HassanRaza1313** [chrislim2888/IP2Location-Python#18]
I have a module in my application where I am showing the geolocation of a user using their IP Address. The sample code for that module is shown below:

![image](https://user-images.githubusercontent.com/61215448/149081966-0db9e4c5-c4f0-4236-93e3-3d306cb5f7d7.png)

I am using IP2Location API (version 8.6.4) on Python 3.6. I am using the paid database (.BIN file) for the lookup, and have recently downloaded the latest database file. As mentioned in the image above, I am inputting the IP Address 76.100.80.65, which is the IP of a user in Frederick, Maryland. However, when I run the code, the output is:

![image](https://user-images.githubusercontent.com/61215448/149082168-9c8beedb-52be-4eb2-98ac-2b40789fefab.png)

These coordinates point to an address in Alexandria, Virginia as shown in Google Maps:

![image](https://user-images.githubusercontent.com/61215448/149082448-109c540c-6988-4c18-a35b-0e43ddb2a068.png)

Kindly help me with this problem. Thank you!

**Comment by ip2location** [comment]
Hi Hassan,

Our customer service has contacted you regarding this issue. Kindly check the email if you haven't do so.
