### ISSUE TITLE
This is not official IP2Location right?

### ISSUE THREAD

**Issue by vstoykov** [chrislim2888/IP2Location-Python#2]
I see that on PyPi latest version is 7.0.3 from 19.10.2015. Last commit here is from 2014. I wanted to contribute some little improvements but this repo is not up to date.

Did you know where I can propose some changes?

**Comment by chrislim2888** [comment]
This is the official python listing. The version is not tag according to pypi, maybe something I shall consider in future.

You may send me a pull request for the propose changes.

**Comment by vstoykov** [comment]
I see that after you accepted my changes you also updated the version here in the repo from 7.0.0 to 7.0.1 but in PyPi it was 7.0.3 before I propose my changes.

Now I need to wait for 7.0.4 on PyPi or I'm missing something?

**Comment by chrislim2888** [comment]
Sorry for late reply, I synced both to 7.0.4.
