### ISSUE TITLE
Please correct your mistakes. Hong Kong is not a country, but a part of China's territory

### ISSUE THREAD

**Issue by ohyeah521** [chrislim2888/IP2Location-Python#21]
Please correct your mistakes. Hong Kong is not a country, but a part of China's territory

I checked the IP address of Hong Kong, but the program returned Hong Kong as the country, which is a major error.
![2022-11-15_081857](https://user-images.githubusercontent.com/1449374/201795335-84bc4196-5f24-4c18-8c78-cb4e9b09408d.jpg)

**Comment by chrislim2888** [comment]
We display the country name based on the ISO3166 naming from iso.org.
