### ISSUE TITLE
File IP2Location.py not found for manual installation of 8.10.1

### ISSUE THREAD

**Issue by simplylu** [chrislim2888/IP2Location-Python#22]
Since the build I get via pip is not working at all, I tried to install 8.10.1 manually from the release you provided.

### Steps to reproduce
1. `wget -c https://github.com/chrislim2888/IP2Location-Python/archive/refs/tags/8.10.1.zip`
2. `unzip 8.10.1.zip`
3. `cd IP2Location-Python-8.10.1`
4. `python3 setup.py build`

### Expected outcome
The build should run without any error so that I can continue with the last step: `python3 setup.py install`

### Actual outcome
```sh
[user@server IP2Location-Python-8.10.1]$ python3 setup.py build
running build
running build_py
file IP2Location.py (for module IP2Location) not found
creating build
creating build/lib
creating build/lib/IP2Location
copying IP2Location/webservice.py -> build/lib/IP2Location
copying IP2Location/region.py -> build/lib/IP2Location
copying IP2Location/iptools.py -> build/lib/IP2Location
copying IP2Location/database.py -> build/lib/IP2Location
copying IP2Location/country.py -> build/lib/IP2Location
copying IP2Location/__init__.py -> build/lib/IP2Location
file IP2Location.py (for module IP2Location) not found
```

### System information
- Python Version: Python 3.6.8 and Python 3.11.5
- OS:  Rocky Linux 8.9 (Green Obsidian)
- Kernel: Linux 4.18.0 x86_64 GNU/Linux

**Comment by ip2location** [comment]
Hi simplylu,

Thanks for opening this issue. We have check this issue and push a fix for it. You can try the 8.10.2 and see if the issue is gone.
P.S.: If the `pip install IP2Location` is not working for you, have you try `pip3 install IP2Location`?

**Comment by simplylu** [comment]
Hi ip2location,
thanks for fixing it that quickly. Now it works.
The installation via `pip3 install --user IP2Location` worked in the past, but then, when loading the BIN file, it said that the BIN file has the wrong format. Which was not true because it was downloaded minutes before.

However, I couldn't reproduce the error, so it might have been fixed.
