### ISSUE TITLE
"struct.error: unpack requires a string argument of length 4" with BIN database file retrieved on September 22, 2017

### ISSUE THREAD

**Issue by afressancourt** [chrislim2888/IP2Location-Python#5]
Hello,

I am encountering an error of type "struct.error: unpack requires a string argument of length 4" while using the IP2Location-8.0.0 module with the IP2LOCATION-LITE-DB11.BIN fiel I retrieved today (September 22nd). The stack trace states the following:
```
File "batch_locate.py", line 302, in locate_ip_i2l
    response = IP2Loc_v4.get_all(ip_addr)
  File "/Users/afressancourt/.virtualenvs/py-multi-geoloc/lib/python2.7/site-packages/IP2Location.py", line 219, in get_all
    return self._get_record(addr)
  File "/Users/afressancourt/.virtualenvs/py-multi-geoloc/lib/python2.7/site-packages/IP2Location.py", line 388, in _get_record
    ipfrom = self._readip(baseaddr + (mid) * (self._dbcolumn * 4 + off), ipv)
  File "/Users/afressancourt/.virtualenvs/py-multi-geoloc/lib/python2.7/site-packages/IP2Location.py", line 248, in _readip
    return self._readi(offset)
  File "/Users/afressancourt/.virtualenvs/py-multi-geoloc/lib/python2.7/site-packages/IP2Location.py", line 240, in _readi
    return struct.unpack('<I', self._f.read(4))[0]
struct.error: unpack requires a string argument of length 4
```

**Comment by ip2location** [comment]
Hi @afressancourt 

May us know the ip_addr you enter is IPv4 or IPv6 IP address?
If it is IPv6 IP address, please get the IPv6 BIN file from http://lite.ip2location.com/database/ip-country-region-city-latitude-longitude-zipcode-timezone

**Comment by heng-zhang-20** [comment]
I also met this problem. @ip2location 

# Conditions:
1. IP2Location==8.9.0
2. BIN file download by command `wget -qO DB3LITEBIN.bin --user-agent="Mozilla/5.0+(compatible;" "https://www.ip2location.com/download?token={MYTOKEN}&code=DB3LITEBIN"`
3. ip = "66.240.205.34"

# More Information
But it will be ok if I lookup this ip from BIN file download from `https://lite.ip2location.com/database/db3-ip-country-region-city` browser page.

Besides, I find that BIN file download by command `wget` is different with BIN file download from browser for same url `https://www.ip2location.com/download?token={MYTOKEN}&code=DB3LITEBIN`. One is about 13MB and another is about 52 MB. 

![image](https://user-images.githubusercontent.com/67679070/232662107-5ddf5f40-9a1c-45da-9ad3-75fe04af065e.png)

So I guess difference between this 2 files cause that error.

**Comment by ip2location** [comment]
Hi heng-zhang-20,

The file downloaded is a compressed file but not the BIN file itself. Therefore, you have to unzip it before use it. Here is the correct command to download it in the right format:
`wget -qO IP2LOCATION-LITE-DB3.BIN.ZIP --user-agent="Mozilla/5.0+(compatible;" "https://www.ip2location.com/download?token={MYTOKEN}&code=DB3LITEBIN"`

Once you have downloaded the compressed file, you will have to unzip it to another directory and then only use it. Hope this helps.

**Comment by heng-zhang-20** [comment]
Yes, I got the right BIN file and it works fine.
